config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root :to => "artists#index" 
  resources :albums
  resources :artists
  resources :songs

end

app/models/album.rb
class Album < ApplicationRecord

    belongs_to :artist
    has_many :songs

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord

    has_many :albums

end

app/models/song.rb
class Song < ApplicationRecord

    belongs_to :album
    
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController

    before_action :set_album, only: %i[show edit update destroy]

    def index
    
        @albums = Album.all

    end

    def show
            
    end

    def new
    
        @album = Album.new
        
    end

    def create

        @album = Album.new(album_params)
        if @album.save
            redirect_to @album
        else
            render :new
        end
    
    end

    def edit
    
    end

    def update

        if @album.update(album_params)
            redirect_to albums_params
        else
            render :edit
        end
    end
    
    def destroy
    
        if @album.destroy
        	flash[:success] = "Album has been successfully deleted"
		else
			flash[:error] = "Album could have not be deleted"
        end
        
        redirect_to albums_path

    end
    

    private

    def album_params

        params.require(:album).permit(:name, :image_url, :released_at, :artist_id)
    
    end

    def set_album

        @album = Album.find(params[:id])
    
    end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base



end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController

    before_action :set_artist, only: %i[show edit update destroy]

    def index
    
        @artists = Artist.all
       
    end

    def show

            
    end

    def new
    
        @artist = Artist.new
        @albums = Album.all
      
    end

    def create

        @artist = Artist.new(artist_params)
        if @artist.save
            redirect_to @artist
        else
            render :new
        end
    
    end

    def edit
        
        @albums = Album.all
                        
    end

    def update

        if @artist.update(artist_params)
            redirect_to artists_params
        else
            render :edit
        end
    end
    
    def destroy
    
        if @artist.destroy
        	flash[:success] = "Artist has been successfully deleted"
		else
			flash[:error] = "Artist could not be deleted"
        end
        
        redirect_to artists_path

    end
    

    private

    def artist_params

        params.require(:artist).permit(:name, :image_url)
    
    end

    def set_artist

        @artist = Artist.find(params[:id])
    
    end

end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/albums/_form.html.erb
<div class="containter m-5" >
    <div class="row">
        <div class="col-6">
        <%= form_for Album.new do |a| %>
            <div>
                <%= a.label :name %><br>
                <%= a.text_field :name %>
            </div>
            <br>
            <div>
                <%= a.label :released_at %><br>
                <%= a.date_field :released_at %>
            </div>
        </div>
        <div class="col-6">
            <div>
                <%= a.label :image_url %><br>
                <%= a.text_area :image_url %>
            </div>
                <%= a.label :artist_id %>
            <div class="form-group">
                <%= a.collection_select(:artist_id, Artist.all, :id, :name, {}, class:"custom-select") %>
            </div>
        </div>

        <div class="col-6">
            <%= a.submit class:"btn btn-primary" %>
        </div>
        <% end %>
    </div>
</div>

app/views/albums/edit.html.erb
<%= render  "form" %>

app/views/albums/index.html.erb
<div class="container m-5">
    <div class="row">
        <% @albums.each do |a| %>
            <div class="col-3">
                <div class="card" style="width: 18rem;">
                    <img src="<%= a.image_url %>" class="card-img-top" alt="...">
                    <div class="card-body">
                        <h5 class="card-title"><%= a.name %></h5>
                        <h5 class="card-title"><%= a.released_at %></h5>
                        <br>
                    </div>
                </div>
            </div>
        <% end %>
    </div>
</div>
<div class="container m-5">
    <div class="row col-md-10"> 
        <!-- Button trigger modal -->
        <%= link_to  "Create Album", new_album_path, class:"btn btn-primary" %> 
    </div>
</div>

app/views/albums/new.html.erb
<%= render  "form" %>

app/views/albums/show.html.erb
<div class="containter m-5" >
    <div class="row">
        <div col-md-4>
            <h1><%= @album.name %></h1>
            <div class="containter m-5" >
                <div class="row">
                    <div col-4>
                        <div class="card" style="width: 18rem;">
                            <img src="<%= @album.image_url %>" class="card-img-top" alt="...">
                            <div class="card-body">
                                <h5 class="card-title"><%= @album.name %></h5>
                                <h5 class="card-title"><%= @album.released_at %></h5>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            
        </div>
    </div>
</div>

app/views/artists/_form.html.erb
<div class="containter m-5" >
        <div class="row">
            <div col-6>
            <%= form_for @artist do |a| %>
                <div>
                    <%= a.label :name %><br>
                    <%= a.text_field :name %>
                </div>
                <br>
                <div>
                    <%= a.label :image_url %><br>
                    <%= a.text_area :image_url %>
                </div>
                <br>
                <div>
                    <%= a.submit class:"btn btn-primary" %>
                </div>
            <% end %>
        </div>
    </div>
</div>

app/views/artists/index.html.erb
<div class="containter m-5" >
    <div class="row">
        <% @artists.each do |artist| %>
            <div class="col-3">
                <div class="card" style="width: 18rem;">
                    <img src="<%= artist.image_url %>" class="card-img-top" alt="...">
                    <div class="card-body" style="text-align: center;">
                        <h5 class="card-title"><%= artist.name %></h5>
                        <%= link_to "Ver Más", artist, class:"btn btn-primary btn-lg btn-block" %>
                    </div>
                </div>
            </div>
        <% end %>
    </div>
</div>
<br>
<!-- <div class="container m-5">
    <div class="row col-md-10"> 
        < Button trigger modal -->
        <!-- <%= link_to  "Create Artist", new_artist_path, class:"btn btn-primary" %> 
    </div>
</div>  -->

app/views/artists/show.html.erb
<div class="containter m-5">
    <div class="row">
        <div class="col-8">
            <h1><%= @artist.name %></h1>
            <br>
            <h5> Albums (<%= @artist.albums.count%>)</h5>
            <br>
            <div class="d-flex flex-wrap">
                <% @artist.albums.each do |album| %>     
                    <div class="bd-highlight" >            
                        <div class="card m-3" style="width:  9rem;">
                            <img src="<%= album.image_url %>" class="card-img-top" alt="foo_fighters">
                            <div class="card-body">
                                <p class="text-left"><%= album.name %></p>
                                <p class="card-text"><%= album.released_at %></p>                            
                            </div>
                        </div>              
                    </div>
                 <% end %>
            </div>  
        </div>       
        <div class="col-md-4">
            <img src="<%= @artist.image_url %>" class="card-img-top" style="width: 100%" alt="...">
        </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MasMusica</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
          <a class="navbar-brand" href="#">Real Music</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarText">
              <ul class="navbar-nav mr-auto">
                  <li class="nav-item active">
                        <%= link_to  "Artists", artists_path, class:"nav-link" %>
                    </li>
                    <li class="nav-item">
                        <%= link_to  "Albums", albums_path, class:"nav-link" %>
                    </li>
              </ul>
              <span class="navbar-text">
                  Mi Cuenta
              </span>
          </div>
      </nav>
    <%= yield %>
  </body>
</html>